/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpay;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JScrollBar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sqlLite.sqlDB;

/**
 *
 * @author chilse
 */
public class cpayMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form cpayMainFrame
     */
    JTable users;
    String dbPath = "F:\\Java\\cpayDB.sqlite";

    public cpayMainFrame() {

        sqlDB dbCon = new sqlDB(dbPath);
        
        initComponents();
        JScrollBar bar = userList.getVerticalScrollBar();
        bar.setPreferredSize(new Dimension(100, 0));
        DefaultTableModel dm = new DefaultTableModel();
        String[] userNames = dbCon.getUser();
        dm.setDataVector(new Object[][]{userNames},
                new Object[]{"Users"});

        users = new JTable(dm);

        users.getColumn("Users").setCellRenderer(new ButtonRenderer());
        users.getColumn("Users").setCellEditor(new ButtonEditor(new JCheckBox()));
        users.setRowHeight(120);
        users.setTableHeader(null);
        //repaint();
        userList.setViewportView(users);

        mainPanel.add(userList);
        pack();
    }

    public class ButtonEditor extends DefaultCellEditor {

        protected JButton button;
        private String label;
        private boolean isPushed;

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setOpaque(true);
            button.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    fireEditingStopped();
                }
            });
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int column) {
            if (isSelected) {
                button.setForeground(table.getSelectionForeground());
                button.setBackground(table.getSelectionBackground());

            } else {
                button.setForeground(table.getForeground());
                button.setBackground(table.getBackground());
            }
            label = (value == null) ? "" : value.toString();
            button.setText(label);
            isPushed = true;
            return button;
        }

        @Override
        public Object getCellEditorValue() {
            if (isPushed) {
                mainPanel.remove(userList);
                mainPanel.add(userPanel);
                usernameField.setText(button.getText());
                pack();
            }
            isPushed = false;
            return label;
        }

        @Override
        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }

        @Override
        protected void fireEditingStopped() {
            super.fireEditingStopped();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userPanel = new javax.swing.JPanel();
        removeCoffee = new javax.swing.JButton();
        addCoffee = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        accountField = new javax.swing.JTextField();
        coffeeCount = new javax.swing.JTextField();
        coffeHeader = new javax.swing.JLabel();
        pay = new javax.swing.JButton();
        settingsButton = new javax.swing.JButton();
        userList = new javax.swing.JScrollPane();
        pinPanel = new javax.swing.JPanel();
        pinPassfield = new javax.swing.JPasswordField();
        pinButton5 = new javax.swing.JButton();
        pinButton8 = new javax.swing.JButton();
        pinButton7 = new javax.swing.JButton();
        pinButton3 = new javax.swing.JButton();
        pinButton4 = new javax.swing.JButton();
        pinButton6 = new javax.swing.JButton();
        pinButton2 = new javax.swing.JButton();
        pinButton0 = new javax.swing.JButton();
        pinButton1 = new javax.swing.JButton();
        pinButton9 = new javax.swing.JButton();
        pinButtonOK = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        pinButtonRemove = new javax.swing.JButton();
        adminPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();

        removeCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/509.png"))); // NOI18N
        removeCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeCoffeeActionPerformed(evt);
            }
        });

        addCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/508.png"))); // NOI18N
        addCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCoffeeActionPerformed(evt);
            }
        });

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/017__circle_close.png"))); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("User:");

        usernameField.setText("Chilse");
        usernameField.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Account Balance:");

        accountField.setText("50 Mark");
        accountField.setEnabled(false);
        accountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountFieldActionPerformed(evt);
            }
        });

        coffeeCount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        coffeeCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        coffeeCount.setText("1");
        coffeeCount.setEnabled(false);

        coffeHeader.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        coffeHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coffeHeader.setText("Coffee Payment");

        pay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pay.setText("PAY");
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });

        settingsButton.setIcon(new javax.swing.ImageIcon("F:\\Java\\Prog\\newIcon\\082__setting_cog.png")); // NOI18N
        settingsButton.setToolTipText("");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userPanelLayout = new javax.swing.GroupLayout(userPanel);
        userPanel.setLayout(userPanelLayout);
        userPanelLayout.setHorizontalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(userPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(coffeHeader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, userPanelLayout.createSequentialGroup()
                            .addComponent(removeCoffee)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(pay, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(coffeeCount))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(addCoffee)))
                    .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountField, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addComponent(usernameField)))))
        );
        userPanelLayout.setVerticalGroup(
            userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userPanelLayout.createSequentialGroup()
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(settingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameField)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountField, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(coffeHeader)
                .addGap(18, 18, 18)
                .addGroup(userPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(removeCoffee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(coffeeCount)
                    .addComponent(addCoffee))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pay, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userList.setPreferredSize(new java.awt.Dimension(4, 4));

        pinPanel.setMinimumSize(new java.awt.Dimension(786, 402));
        pinPanel.setPreferredSize(new java.awt.Dimension(786, 402));

        pinPassfield.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pinPassfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        pinButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton5.setText("5");
        pinButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton5ActionPerformed(evt);
            }
        });

        pinButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton8.setText("8");
        pinButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton8ActionPerformed(evt);
            }
        });

        pinButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton7.setText("7");
        pinButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton7ActionPerformed(evt);
            }
        });

        pinButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton3.setText("3");
        pinButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton3ActionPerformed(evt);
            }
        });

        pinButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton4.setText("4");
        pinButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton4ActionPerformed(evt);
            }
        });

        pinButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton6.setText("6");
        pinButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton6ActionPerformed(evt);
            }
        });

        pinButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton2.setText("2");
        pinButton2.setToolTipText("");
        pinButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton2ActionPerformed(evt);
            }
        });

        pinButton0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton0.setText("0");
        pinButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton0ActionPerformed(evt);
            }
        });

        pinButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton1.setText("1");
        pinButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton1ActionPerformed(evt);
            }
        });

        pinButton9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButton9.setText("9");
        pinButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton9ActionPerformed(evt);
            }
        });

        pinButtonOK.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButtonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/100__key.png"))); // NOI18N
        pinButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButtonOKActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("enter security PIN");

        pinButtonRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        pinButtonRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/011__circle_arrow_left.png"))); // NOI18N
        pinButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButtonRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pinPanelLayout = new javax.swing.GroupLayout(pinPanel);
        pinPanel.setLayout(pinPanelLayout);
        pinPanelLayout.setHorizontalGroup(
            pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinPanelLayout.createSequentialGroup()
                .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pinPanelLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinPanelLayout.createSequentialGroup()
                                .addComponent(pinButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pinButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinPanelLayout.createSequentialGroup()
                                .addComponent(pinButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pinButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pinPanelLayout.createSequentialGroup()
                                .addComponent(pinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pinButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pinButton0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pinButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(pinButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(pinButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(pinButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                    .addGroup(pinPanelLayout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pinPanelLayout.createSequentialGroup()
                                .addComponent(pinPassfield, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pinButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(229, Short.MAX_VALUE))
        );
        pinPanelLayout.setVerticalGroup(
            pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinPassfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButtonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinButton0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pinButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        adminPanel.setMinimumSize(new java.awt.Dimension(786, 402));

        javax.swing.GroupLayout adminPanelLayout = new javax.swing.GroupLayout(adminPanel);
        adminPanel.setLayout(adminPanelLayout);
        adminPanelLayout.setHorizontalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 786, Short.MAX_VALUE)
        );
        adminPanelLayout.setVerticalGroup(
            adminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCoffeeActionPerformed
        int cc = Integer.parseInt(coffeeCount.getText());
        if (cc > 1) {
            cc--;
        }
        coffeeCount.setText(cc + "");
    }//GEN-LAST:event_removeCoffeeActionPerformed

    private void addCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCoffeeActionPerformed
        int cc = Integer.parseInt(coffeeCount.getText());
        cc++;
        coffeeCount.setText(cc + "");

    }//GEN-LAST:event_addCoffeeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        mainPanel.remove(userPanel);
        mainPanel.add(userList);
        pack();
    }//GEN-LAST:event_exitActionPerformed

    private void accountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountFieldActionPerformed

    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void pinButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton5ActionPerformed

    private void pinButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton8ActionPerformed

    private void pinButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton7ActionPerformed

    private void pinButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton3ActionPerformed

    private void pinButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton4ActionPerformed

    private void pinButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton6ActionPerformed

    private void pinButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton2ActionPerformed

    private void pinButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton0ActionPerformed

    private void pinButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton1ActionPerformed

    private void pinButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButton9ActionPerformed

    private void pinButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButtonOKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButtonOKActionPerformed

    private void pinButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButtonRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinButtonRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cpayMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cpayMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cpayMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cpayMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new cpayMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountField;
    private javax.swing.JButton addCoffee;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JLabel coffeHeader;
    private javax.swing.JTextField coffeeCount;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton pay;
    private javax.swing.JButton pinButton0;
    private javax.swing.JButton pinButton1;
    private javax.swing.JButton pinButton2;
    private javax.swing.JButton pinButton3;
    private javax.swing.JButton pinButton4;
    private javax.swing.JButton pinButton5;
    private javax.swing.JButton pinButton6;
    private javax.swing.JButton pinButton7;
    private javax.swing.JButton pinButton8;
    private javax.swing.JButton pinButton9;
    private javax.swing.JButton pinButtonOK;
    private javax.swing.JButton pinButtonRemove;
    private javax.swing.JPanel pinPanel;
    private javax.swing.JPasswordField pinPassfield;
    private javax.swing.JButton removeCoffee;
    private javax.swing.JButton settingsButton;
    private javax.swing.JScrollPane userList;
    private javax.swing.JPanel userPanel;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
